englishKids/config/routes.rb
Rails.application.routes.draw do
  get 'entertainments/index'

  get 'entertainments/show'
  resources :entertainments
  root 'page#index'
  resources :sub_quizzes
  resources :quizzes
  resources :vocabularies do
    resources :vocabulary_examples
    resources :quizzes
  end
  resources :pronunciation_examples do
    resources :quizzes
  end

  resources :pronunciations 
  
  resources :subjects do
   resources :parts
    resources :quizzes
  end
   resources :parts do
      resources :details
    end

 

end

englishKids/app/models/detail.rb
class Detail < ActiveRecord::Base
	belongs_to :part
end

englishKids/app/models/entertainment.rb
class Entertainment < ActiveRecord::Base
	has_many :sub_entertainments
end

englishKids/app/models/part.rb
class Part < ActiveRecord::Base
	belongs_to :subject
	has_many :details
end

englishKids/app/models/pronunciation.rb
class Pronunciation < ActiveRecord::Base
	has_many :pronunciation_examples
	has_many :quizzes
end

englishKids/app/models/pronunciation_example.rb
class PronunciationExample < ActiveRecord::Base
	belongs_to :pronunciation

end

englishKids/app/models/quiz.rb
class Quiz < ActiveRecord::Base
	has_many :sub_quizzes
	belongs_to :subject
	belongs_to :pronunciation
	belongs_to :vocabulary
end

englishKids/app/models/sub_entertainment.rb
class SubEntertainment < ActiveRecord::Base
	belongs_to :entertainment
end

englishKids/app/models/sub_quiz.rb
class SubQuiz < ActiveRecord::Base
	belongs_to :quiz
end

englishKids/app/models/subject.rb
class Subject < ActiveRecord::Base
	has_many :parts
	has_many :quizzes
end

englishKids/app/models/vocabulary.rb
class Vocabulary < ActiveRecord::Base
	has_many :vocabulary_examples
	has_many :quizzes
end

englishKids/app/models/vocabulary_example.rb
class VocabularyExample < ActiveRecord::Base
	belongs_to :vocabulary

end

englishKids/app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
  end
end

englishKids/app/controllers/parts_controller.rb
class PartsController < ApplicationController
	layout 'layout'
  def index
  	@subject = Subject.find(params[:subject_id])
  	@quiz = Quiz.find(params[:subject_id])
    @parts = @subject.parts.all
    # @details =  @parts.details.all
  end

  def show
  	
  end
end

englishKids/app/controllers/pronunciations_controller.rb
class PronunciationsController < ApplicationController
	layout 'layout'
  def index
  	@short_vowels = Pronunciation.where(:role => 'short vowel').all
  	@long_vowels = Pronunciation.where(:role => 'long vowel').all
  	@diphthong_vowels = Pronunciation.where(:role => 'diphthong vowel').all
  	@consonant_vowels = Pronunciation.where(:role => 'consonant vowel').all
  	# @pronunciation_example = PronunciationExample.find(params[:pronunciation_id])
  	# @pronunciation_example = PronunciationExample.find(:id => 1)
    @compare_sounds = Pronunciation.where(:role => 'compare sound').all
    @t = 'pro'
    
  end
  def show
  end
end

englishKids/app/helpers/application_helper.rb
module ApplicationHelper
end

englishKids/app/helpers/details_helper.rb
module DetailsHelper
end

englishKids/app/helpers/page_helper.rb
module PageHelper
end

englishKids/app/helpers/parts_helper.rb
module PartsHelper
end

englishKids/app/helpers/pronunciations_helper.rb
module PronunciationsHelper
end

englishKids/app/helpers/quizzes_helper.rb
module QuizzesHelper
end

englishKids/app/helpers/sub_quizzes_helper.rb
module SubQuizzesHelper
end

englishKids/app/helpers/subjects_helper.rb
module SubjectsHelper
end

englishKids/app/helpers/vocabularies_helper.rb
module VocabulariesHelper
end

englishKids/app/views/pronunciations/index.html.erb
<div class="container">
  <div class="row">
    <div role="tabpanel">
      <!-- Nav tabs -->
      <ul class="nav nav-tabs pull-right" role="tablist">
        <li role="presentation" class="active item"><a href="#home" aria-controls="home" role="tab" data-toggle="tab" class="item-vowel">Vowel</a></li>
        <li role="presentation" class="item"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">Compare Sound</a></li>
      </ul>
      <!-- Tab panes -->
      <div class="tab-content">
        <div role="tabpanel" class="tab-pane active row" id="home">
          <fieldset class="scheduler-border">
            <legend class="scheduler-border">Short Vowel</legend>
            <div class="control-group">
              <%=@short_vowels.each_slice(5) do |slice_of_six|%>
              <div class="row box">
                <%slice_of_six.each do |short_vowel|%>
                <div class="col-md-2  item-letter">
                  <%= link_to image_tag(short_vowel.img, class: "border-image-pronunciation"), pronunciation_example_path(short_vowel) %>
                </div>
                <%end%>
              </div>
              <%end%>
            </div>
          </fieldset>
          <fieldset class="scheduler-border">
            <legend class="scheduler-border">Long Vowel</legend>
            <div class="control-group">
              <%=@long_vowels.each_slice(5) do |slice_of_six|%>
              <div class="row box">
                <%slice_of_six.each do |long_vowel|%>
                <div class="col-md-2  item-letter">
                  <%= link_to image_tag(long_vowel.img, class: "border-image-pronunciation"), pronunciation_example_path(long_vowel) %>
                </div>
                <%end%>
              </div>
              <%end%>
            </div>
          </fieldset>
          <fieldset class="scheduler-border">
            <legend class="scheduler-border">Diphthong Vowel</legend>
            <div class="control-group">
              <%=@diphthong_vowels.each_slice(5) do |slice_of_six|%>
              <div class="row box">
                <%slice_of_six.each do |diphthong_vowel|%>
                <div class="col-md-2  item-letter">
                  <%= link_to image_tag(diphthong_vowel.img, class: "border-image-pronunciation"), pronunciation_example_path(diphthong_vowel) %>
                </div>
                <%end%>
              </div>
              <%end%>
            </div>
          </fieldset>
          <fieldset class="scheduler-border">
            <legend class="scheduler-border">Consonant Vowel</legend>
            <div class="control-group">
              <%=@consonant_vowels.each_slice(5) do |slice_of_six|%>
              <div class="row box">
                <%slice_of_six.each do |consonant_vowel|%>
                <div class="col-md-2  item-letter">
                  <%= link_to image_tag(consonant_vowel.img, class: "border-image"), pronunciation_example_path(consonant_vowel) %>
                </div>
                <%end%>
              </div>
              <%end%>
            </div>
          </fieldset>
        </div>
        <div role="tabpanel" class="tab-pane" id="profile">
          <fieldset class="scheduler-border">
            <legend class="scheduler-border">Compare Sound</legend>
            <div class="control-group">
              <%=@compare_sounds.each_slice(3) do |slice_of_six|%>
              <div class="row box">
              
                <%slice_of_six.each do |compare_sound|%>
                <div class="col-md-3  item-letter">
                  <%= link_to image_tag(compare_sound.img, class: "border-image"), pronunciation_examples_path(compare_sound)%>
                  <figcaption class="text-compare"><%=compare_sound.name%></figcaption>
                </div>
                <%end%>
              </div>
              <%end%>
            </div>
          </fieldset>
        </div>
        <div role="tabpanel" class="tab-pane" id="messages">.3..</div>
      </div>
    </div>
  </div>
</div>