main-Project/englishKids/config/routes.rb
Rails.application.routes.draw do
  root 'page#index'
  resources :sub_quizzes
  resources :quizzes
  resources :vocabularies
  resources :vocabulary_examples
  resources :pronunciation_examples
  resources :pronunciations
  resources :subjects
  resources :details
  resources :parts

 

end

main-Project/englishKids/app/models/detail.rb
class Detail < ActiveRecord::Base
	belongs_to :subject
	belongs_to :part
	
end

main-Project/englishKids/app/models/part.rb
class Part < ActiveRecord::Base
	has_many :details
end

main-Project/englishKids/app/models/pronunciation.rb
class Pronunciation < ActiveRecord::Base
	has_many :pronunciation_examples
	has_many :quizzes
end

main-Project/englishKids/app/models/pronunciation_example.rb
class PronunciationExample < ActiveRecord::Base
	belongs_to :pronunciation

end

main-Project/englishKids/app/models/quiz.rb
class Quiz < ActiveRecord::Base
	has_many :sub_quizzes
	belongs_to :subject
	belongs_to :pronunciation
	belongs_to :vocabulary
end

main-Project/englishKids/app/models/sub_quiz.rb
class SubQuiz < ActiveRecord::Base
	belongs_to :quiz
end

main-Project/englishKids/app/models/subject.rb
class Subject < ActiveRecord::Base
	has_many :details
	has_many :quizzes
end

main-Project/englishKids/app/models/vocabulary.rb
class Vocabulary < ActiveRecord::Base
	has_many :vocabulary_examples
	has_many :quizzes
end

main-Project/englishKids/app/models/vocabulary_example.rb
class VocabularyExample < ActiveRecord::Base
	belongs_to :vocabulary

end

main-Project/englishKids/app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
  end
end

main-Project/englishKids/app/controllers/parts_controller.rb
class PartsController < ApplicationController
  def index
  end
end

main-Project/englishKids/app/helpers/application_helper.rb
module ApplicationHelper
end

main-Project/englishKids/app/helpers/details_helper.rb
module DetailsHelper
end

main-Project/englishKids/app/helpers/page_helper.rb
module PageHelper
end

main-Project/englishKids/app/helpers/parts_helper.rb
module PartsHelper
end

main-Project/englishKids/app/helpers/pronunciations_helper.rb
module PronunciationsHelper
end

main-Project/englishKids/app/helpers/quizzes_helper.rb
module QuizzesHelper
end

main-Project/englishKids/app/helpers/sub_quizzes_helper.rb
module SubQuizzesHelper
end

main-Project/englishKids/app/helpers/subjects_helper.rb
module SubjectsHelper
end

main-Project/englishKids/app/helpers/vocabularies_helper.rb
module VocabulariesHelper
end

main-Project/englishKids/app/views/page/index.html.erb
   <!-- <script src="/assets/main.js"></script>
  // <script src="/assets/loadpage.js"></script> -->
<section class="header-index">
	<div class="container">
		<div class="row">
			<div class="col-md-3">
				<%= link_to image_tag('logo-index1.png'), vocabularies_path %>
				<!-- <img src="assets/logo-indéx.png"> -->
				<h3 class="text-voca">Vocabulary</h3>
			</div>
			<div class="col-md-3">
				<%= link_to image_tag('logo-index1.png'), subjects_path %>
				<!-- <img src="assets/logo-indéx.png"> -->
				<h3 class="text-subject">Subject</h3>
			</div>
			<div class="col-md-3">
				<%= link_to image_tag('logo-index1.png'), 'vocabularies/index' %>
				<!-- <img src="assets/logo-indéx.png"> -->
				<h3 class="text-pro">Pronunciation</h3>
			</div>
			<div class="col-md-3">
				<%= link_to image_tag('logo-index1.png'), 'vocabularies/index' %>
				<!-- <img src="assets/logo-indéx.png"> -->
				<h3 class="text-enter">Entertaiment</h3>
			</div>
		</div>
	</div>
	  <script src="/assets/main.js"></script>
	  <script src="/assets/loadpage.js"></script>
</section>

main-Project/englishKids/app/views/page/itemVocabulary.html.erb
<body class="index">
	<header class="header-main container-fluid ">
		<div class="logo row">
			<div class="col-md-1">
				<a href="#"><img src="../assets/logo.png"></a>
			</div>
			<div class="col-md-5">
				<h1 class="text-3d">English for Kids</h1>
			</div>
			<div class="col-md-6">
				<ul class="header-right pull-right">
		      <li><button type="button" class="btn btn-default text-button "><%= link_to "Vocabulary", root_path, class: "button-main btn-focus"%></button></li>
		      <li><button type="button" class="btn btn-default text-button"><%= link_to "Subject", root_path, class: "button-main"%></button></li>
       <li ><button type="button" class="btn btn-default text-button"><%= link_to "Pronunciation", root_path, class: "button-main"%></button></li>
        <li><button type="button" class="btn btn-default text-button"><%= link_to "Entertaiment", root_path, class: "button-main"%></button></li>
    		</ul>
			</div>
		</div>
	</header>

	<section>
		<div class="container">
			
			<div class="row list-item">
				<div class="col-md-2 title-item">
					<%= image_tag "a.png", class: ""%>
						<button type="button" class="btn btn-default text-button"><%= link_to "Go to Quiz", root_path, class: "button-main"%>
				</div>
				<div class="col-md-3">
					 <%= image_tag "ant.png", class: "list-image"%>
						<p class="desc">
							<span>Ant- Con kien</span>
	            <audio id="1">
	              <source src='1' type='audio/mpeg'/>
	            </audio>
	            <a id="2" class="play-audio" href="JavaScript:void(0)">
	            <i class="fa fa-volume-up fa-2 play" ></i>
	            <i class="fa fa-volume-up fa-2 pause"></i>
	            </a>
	          </p>
				</div>
				<div class="col-md-3">
					<%= image_tag "alligator.png", class: "list-image"%>
						<p class="desc">
							<span>Alligator- Ca sau</span>
	            <audio id="1">
	              <source src='1' type='audio/mpeg'/>
	            </audio>
	            <a id="2" class="play-audio" href="JavaScript:void(0)">
	            <i class="fa fa-volume-up fa-2 play"></i>
	            <i class="fa fa-volume-up fa-2 pause"></i>
	            </a>
	          </p>
				</div>
				<div class="col-md-3">
					<%= image_tag "apple.png", class: "list-image"%>
					<p class="desc">
						<span>Apple- Qua tao</span>
            <audio id="1">
              <source src='1' type='audio/mpeg'/>
            </audio>
            <a id="2" class="play-audio" href="JavaScript:void(0)">
            <i class="fa fa-volume-up fa-2 play"></i>
            <i class="fa fa-volume-up fa-2 pause"></i>
            </a>
          </p>
				</div>
			</div>
			<div class="row btn-list">
				<div class="col-md-1 col-md-offset-2">
					<button type="button" class="btn btn-default text-button"><%= link_to "Back", root_path, class: "button-main"%>
				</div>
				<div class="col-md-1 col-md-offset-6">
					<button type="button" class="btn btn-default text-button"><%= link_to "Next", root_path, class: "button-main"%>
				</div>
			</div>
		</div>
	</section>
	
</body>

main-Project/englishKids/app/views/page/vocabulary.html.erb
<body class="index">
	<header class="header-main container-fluid ">
		<div class="logo row">
			<div class="col-md-1">
				<a href="#"><img src="../assets/logo.png"></a>
			</div>
			<div class="col-md-5">
				<h1 class="text-3d">English for Kids</h1>
			</div>
			<div class="col-md-6">
				<ul class="header-right pull-right">
		      <li><button type="button" class="btn btn-default text-button"><%= link_to "Vocabulary", root_path, class: "button-main"%></button></li>
		      <li><button type="button" class="btn btn-default text-button"><%= link_to "Subject", root_path, class: "button-main"%></button></li>
       <li ><button type="button" class="btn btn-default text-button"><%= link_to "Pronunciation", root_path, class: "button-main"%></button></li>
        <li><button type="button" class="btn btn-default text-button"><%= link_to "Entertaiment", root_path, class: "button-main"%></button></li>
    		</ul>
			</div>
		</div>
	</header>
	<section>
		<div class="container">
			<div class="row box">
				<!-- <div class="box"> -->
					<div class="col-md-2 col-md-offset-1 item-letter">
					<%= link_to image_tag('a.png', class: "border-image"), 'itemVocabulary' %>
				</div>
				<div class="col-md-2 item-letter">
					<%= link_to image_tag('b.png', class: "border-image"), 'page/vocabulary' %>
				</div>
				<div class="col-md-2 item-letter">
					<%= link_to image_tag('c.png', class: "border-image"), 'page/vocabulary' %>
				</div>
				<div class="col-md-2 item-letter">
					<%= link_to image_tag('d.png', class: "border-image"), 'page/vocabulary' %>
				</div>
				<div class="col-md-2 item-letter">
					<%= link_to image_tag('e.png', class: "border-image"), 'page/vocabulary' %>
				</div>
				<!-- </div> -->
				
			</div>

			<div class="row box">
				<div class="col-md-2 col-md-offset-1 item-letter">
					<%= link_to image_tag('f.png', class: "border-image"), 'page/vocabulary' %>
				</div>
				<div class="col-md-2 item-letter">
					<%= link_to image_tag('g.png', class: "border-image"), 'page/vocabulary' %>
				</div>
				<div class="col-md-2 item-letter">
					<%= link_to image_tag('h.png', class: "border-image"), 'page/vocabulary' %>
				</div>
				<div class="col-md-2 item-letter">
					<%= link_to image_tag('i.png', class: "border-image"), 'page/vocabulary' %>
				</div>
				<div class="col-md-2 item-letter">
					<%= link_to image_tag('j.png', class: "border-image"), 'page/vocabulary' %>
				</div>
			</div>

			<div class="row box">
				<div class="col-md-2 col-md-offset-1 item-letter">
					<%= link_to image_tag('a.png', class: "border-image"), 'page/vocabulary' %>
				</div>
				<div class="col-md-2 item-letter">
					<%= link_to image_tag('a.png', class: "border-image"), 'page/vocabulary' %>
				</div>
				<div class="col-md-2 item-letter">
					<%= link_to image_tag('a.png', class: "border-image"), 'page/vocabulary' %>
				</div>
				<div class="col-md-2 item-letter">
					<%= link_to image_tag('a.png', class: "border-image"), 'page/vocabulary' %>
				</div>
				<div class="col-md-2 item-letter">
					<%= link_to image_tag('a.png', class: "border-image"), 'page/vocabulary' %>
				</div>
			</div>


			<div class="row box">
				<div class="col-md-2 col-md-offset-1 item-letter">
					<%= link_to image_tag('a.png', class: "border-image"), 'page/vocabulary' %>
				</div>
				<div class="col-md-2 item-letter">
					<%= link_to image_tag('a.png', class: "border-image"), 'page/vocabulary' %>
				</div>
				<div class="col-md-2 item-letter">
					<%= link_to image_tag('a.png', class: "border-image"), 'page/vocabulary' %>
				</div>
				<div class="col-md-2 item-letter">
					<%= link_to image_tag('a.png', class: "border-image"), 'page/vocabulary' %>
				</div>
				<div class="col-md-2 item-letter">
					<%= link_to image_tag('a.png', class: "border-image"), 'page/vocabulary' %>
				</div>
			</div>

			<div class="row box">
				<div class="col-md-2 col-md-offset-1 item-letter">
					<%= link_to image_tag('a.png', class: "border-image"), 'page/vocabulary' %>
				</div>
				<div class="col-md-2 item-letter">
					<%= link_to image_tag('a.png', class: "border-image"), 'page/vocabulary' %>
				</div>
				<div class="col-md-2 item-letter">
					<%= link_to image_tag('a.png', class: "border-image"), 'page/vocabulary' %>
				</div>
				<div class="col-md-2 item-letter">
					<%= link_to image_tag('a.png', class: "border-image"), 'page/vocabulary' %>
				</div>
				<div class="col-md-2 item-letter">
					<%= link_to image_tag('a.png', class: "border-image"), 'page/vocabulary' %>
				</div>
			</div>
		</div>
	</section>
	
</body>