englishKids/config/routes.rb
Rails.application.routes.draw do
  get 'entertainments/index'

  get 'entertainments/show'
  resources :entertainments
  root 'page#index'
  resources :sub_quizzes
  resources :quizzes
  resources :vocabularies do
    resources :vocabulary_examples
    resources :quizzes
  end
  resources :pronunciation_examples do
    resources :quizzes
  end

  resources :pronunciations 
  
  resources :subjects do
   resources :parts
    resources :quizzes
  end
   resources :parts do
      resources :details
    end

 

end

englishKids/app/models/detail.rb
class Detail < ActiveRecord::Base
	belongs_to :part
end

englishKids/app/models/entertainment.rb
class Entertainment < ActiveRecord::Base
	has_many :sub_entertainments
end

englishKids/app/models/part.rb
class Part < ActiveRecord::Base
	belongs_to :subject
	has_many :details
end

englishKids/app/models/pronunciation.rb
class Pronunciation < ActiveRecord::Base
	has_many :pronunciation_examples
	has_many :quizzes
end

englishKids/app/models/pronunciation_example.rb
class PronunciationExample < ActiveRecord::Base
	belongs_to :pronunciation

end

englishKids/app/models/quiz.rb
class Quiz < ActiveRecord::Base
	has_many :sub_quizzes
	belongs_to :subject
	belongs_to :pronunciation
	belongs_to :vocabulary
end

englishKids/app/models/sub_entertainment.rb
class SubEntertainment < ActiveRecord::Base
	belongs_to :entertainment
end

englishKids/app/models/sub_quiz.rb
class SubQuiz < ActiveRecord::Base
	belongs_to :quiz
end

englishKids/app/models/subject.rb
class Subject < ActiveRecord::Base
	has_many :parts
	has_many :quizzes
end

englishKids/app/models/vocabulary.rb
class Vocabulary < ActiveRecord::Base
	has_many :vocabulary_examples
	has_many :quizzes
end

englishKids/app/models/vocabulary_example.rb
class VocabularyExample < ActiveRecord::Base
	belongs_to :vocabulary

end

englishKids/app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
  end
end

englishKids/app/controllers/parts_controller.rb
class PartsController < ApplicationController
	layout 'layout'
  def index
  	@subject = Subject.find(params[:subject_id])
  	@quiz = Quiz.find(params[:subject_id])
    @parts = @subject.parts.all
    # @details =  @parts.details.all
  end

  def show
  	
  end
end

englishKids/app/controllers/vocabulary_examples_controller.rb
class VocabularyExamplesController < ApplicationController
	layout 'layout'
  def index
  	@vocabulary = Vocabulary.find(params[:vocabulary_id])
    @vocabulary_examples = @vocabulary.vocabulary_examples.all.paginate(:page => params[:page], per_page: 3)
    # gon.vocabulary_examples = VocabularyExample.all
    # gon.details = Detail.all
    @items = []
    @vocabulary_examples.map do |e|
      obj = {
        index: e.index,
        id: e.id,
      }
      @items << obj
      # <p id="item" class="hidden"><%= @items.to_json%>
  end
end
  def show
  	
  end
end

englishKids/app/helpers/application_helper.rb
module ApplicationHelper
end

englishKids/app/helpers/details_helper.rb
module DetailsHelper
end

englishKids/app/helpers/page_helper.rb
module PageHelper
end

englishKids/app/helpers/parts_helper.rb
module PartsHelper
end

englishKids/app/helpers/quizzes_helper.rb
module QuizzesHelper
end

englishKids/app/helpers/sub_quizzes_helper.rb
module SubQuizzesHelper
end

englishKids/app/helpers/subjects_helper.rb
module SubjectsHelper
end

englishKids/app/helpers/vocabularies_helper.rb
module VocabulariesHelper
end

englishKids/app/helpers/vocabulary_examples_helper.rb
module VocabularyExamplesHelper
end

englishKids/app/views/vocabulary_examples/index.html.erb
<section>

<p id="item" class="hidden"><%=raw @items.to_json%>
		<div class="container">
		<%=@vocabulary_examples.each_slice(3) do |slice_of_three|%>
			<div class="row list-item">
				<div class="col-md-2 title-item">
					<!-- <%= image_tag "#{@vocabulary.img}"%> -->
					<%= link_to image_tag(@vocabulary.img), vocabularies_path%>
						<button type="button" class="btn btn-default text-button"><%= link_to "Go to Quiz", vocabulary_quizzes_path(@vocabulary), class: "button-main"%></button>
				</div>
				<%slice_of_three.each do |vocabulary_example|%>
				<div class="col-md-3">
					 <%= image_tag "#{vocabulary_example.img}", class: "list-image"%>
						<p class="desc">
							<span><%=vocabulary_example.word%> - <%=vocabulary_example.translate.force_encoding("UTF-8")%></span>
	            <audio id="vocabulary<%=vocabulary_example.index+vocabulary_example.id.to_s()%>">
	              <source src='<%=vocabulary_example.source%>' type='audio/mpeg'/>
	            </audio>
	            <a id="vocabulary<%= vocabulary_example.id.to_s()%>" class="play-audio" href="JavaScript:void(0)">
	            <i class="fa fa-volume-up fa-2 play pl_<%=vocabulary_example.id%>" ></i>
	            <i class="fa fa-volume-up fa-2 pause pau__<%=vocabulary_example.id%>"></i>
	            </a>
	          </p>
				</div>
				<%end%>
				<!-- <div class="row btn-list">
					<input  type="button" class="back" value="Back" /> 
					<input  type="button" class="next" value="Next" />
				</div> -->
		</div>
		<%end%>
		<input  type="button" class="back-vocabulary" value="Back"/> 
		<div class="pull-right"><%= will_paginate @vocabulary_examples, :page_links => false%> </div>
	</section>
	

englishKids/app/views/vocabulary_examples/show.html.erb
<section>

		<div class="container">
			<div class="row list-item">
				<div class="col-md-2 title-item">
					<!-- <%= image_tag "#{@vocabulary.img}"%> -->
					<%= link_to image_tag(@vocabulary.img), vocabularies_path%>
						<button type="button" class="btn btn-default text-button"><%= link_to "Go to Quiz", quiz_path(@vocabulary), class: "button-main"%>
				</div>
				<%@vocabulary_examples.each do |vocabulary_example|%>
				<div class="col-md-3">
					 <%= image_tag "#{vocabulary_example.img}", class: "list-image"%>
						<p class="desc">
							<span><%=vocabulary_example.word%> - <%=vocabulary_example.translate.force_encoding("UTF-8")%></span>
	            <audio id="<%=vocabulary_example.index+vocabulary_example.id.to_s()%>">
	              <source src='<%=vocabulary_example.source%>' type='audio/mpeg'/>
	            </audio>
	            <a id="<%= vocabulary_example.id.to_s()%>" class="play-audio" href="JavaScript:void(0)">
	            <i class="fa fa-volume-up fa-2 play" ></i>
	            <i class="fa fa-volume-up fa-2 pause"></i>
	            </a>
	          </p>
				</div>
				<%end%>
				<div class="row btn-list">
					<input  type="button" class="back" value="Back" /> 
					<input  type="button" class="next" value="Next" />
				</div>
		</div>
	</section>