main-Project/englishKids/config/routes.rb
Rails.application.routes.draw do
  root 'page#index'
  resources :sub_quizzes
  resources :quizzes
  resources :vocabularies
  resources :vocabulary_examples
  resources :pronunciation_examples
  resources :pronunciations
  resources :subjects
  resources :details
  resources :parts

 

end

main-Project/englishKids/app/models/detail.rb
class Detail < ActiveRecord::Base
	belongs_to :subject
	belongs_to :part
	
end

main-Project/englishKids/app/models/part.rb
class Part < ActiveRecord::Base
	has_many :details
end

main-Project/englishKids/app/models/pronunciation.rb
class Pronunciation < ActiveRecord::Base
	has_many :pronunciation_examples
	has_many :quizzes
end

main-Project/englishKids/app/models/pronunciation_example.rb
class PronunciationExample < ActiveRecord::Base
	belongs_to :pronunciation

end

main-Project/englishKids/app/models/quiz.rb
class Quiz < ActiveRecord::Base
	has_many :sub_quizzes
	belongs_to :subject
	belongs_to :pronunciation
	belongs_to :vocabulary
end

main-Project/englishKids/app/models/sub_quiz.rb
class SubQuiz < ActiveRecord::Base
	belongs_to :quiz
end

main-Project/englishKids/app/models/subject.rb
class Subject < ActiveRecord::Base
	has_many :details
	has_many :quizzes
end

main-Project/englishKids/app/models/vocabulary.rb
class Vocabulary < ActiveRecord::Base
	has_many :vocabulary_examples
	has_many :quizzes
end

main-Project/englishKids/app/models/vocabulary_example.rb
class VocabularyExample < ActiveRecord::Base
	belongs_to :vocabulary

end

main-Project/englishKids/app/controllers/details_controller.rb
class DetailsController < ApplicationController
  def index
  end
end

main-Project/englishKids/app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
  end
end

main-Project/englishKids/app/controllers/parts_controller.rb
class PartsController < ApplicationController
  def index
  end
end

main-Project/englishKids/app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
	layout 'layout'
  def index
  end
  def show
  	@quizzes = Quiz.where(:vocabulary_id => params[:id]).all.paginate(:page => params[:page], per_page: 1)
  	gon.quizzes = Quiz.where(:vocabulary_id => params[:id]).all
  	@sub_quizzes = SubQuiz.all
  	gon.sub_quizzes = SubQuiz.all
  end
end

main-Project/englishKids/app/controllers/vocabularies_controller.rb
class VocabulariesController < ApplicationController
	layout 'layout'
  def index
  	@vocabularies = Vocabulary.all
  end
  def show
  	
  	
  end
end

main-Project/englishKids/app/helpers/application_helper.rb
module ApplicationHelper
end

main-Project/englishKids/app/helpers/details_helper.rb
module DetailsHelper
end

main-Project/englishKids/app/helpers/page_helper.rb
module PageHelper
end

main-Project/englishKids/app/helpers/parts_helper.rb
module PartsHelper
end

main-Project/englishKids/app/helpers/pronunciations_helper.rb
module PronunciationsHelper
end

main-Project/englishKids/app/helpers/quizzes_helper.rb
module QuizzesHelper
end

main-Project/englishKids/app/helpers/sub_quizzes_helper.rb
module SubQuizzesHelper
end

main-Project/englishKids/app/helpers/subjects_helper.rb
module SubjectsHelper
end

main-Project/englishKids/app/helpers/vocabularies_helper.rb
module VocabulariesHelper
end

main-Project/englishKids/app/views/vocabularies/index.html.erb
<section>
		<div class="container">
		<%=@vocabularies.each_slice(6) do |slice_of_five|%>
			<div class="row box">
			<%slice_of_five.each do |vocabulary|%>
				<div class="col-md-2  item-letter">
					<%= link_to image_tag(vocabulary.img, class: "border-image"), vocabulary_example_path(vocabulary) %>
				</div>
				<%end%>
			</div>
		<%end%>
		</div>
	</section>
	

main-Project/englishKids/app/views/vocabularies/show.html.erb
<!--   // <script src="/assets/main.js"></script>
  // <script src="/assets/loadpage.js"></script> -->
<section>
		<div class="container">
		<%=@vocabularies.each_slice(6) do |slice_of_five|%>
			<div class="row box">
			<%slice_of_five.each do |vocabulary|%>
				<div class="col-md-2  item-letter">
					<%= link_to image_tag(vocabulary.img, class: "border-image"), vocabulary_examples_index_path(vocabulary) %>
				</div>
				<%end%>
			</div>
		<%end%>
		</div>
	</section>
	